-- Create DataBaseCarlink
CREATE DATABASE DBCarlink;
USE DBCarlink ;

-- Table CLI_CLIENTE
CREATE TABLE CLI_CLIENTE (
  CLI_ID INT PRIMARY KEY AUTO_INCREMENT,
  CLI_NOME VARCHAR(80) NOT NULL,
  CLI_EMAIL VARCHAR(45) NOT NULL UNIQUE,
  CLI_TELEFONE VARCHAR(45) NOT NULL,
  CLI_CPF INT NOT NULL
  );

-- Table MEC_MECANICO
CREATE TABLE MEC_MECANICO (
  MEC_ID INT PRIMARY KEY AUTO_INCREMENT,
  MEC_NOME VARCHAR(80) NOT NULL,
  MEC_EMAIL VARCHAR(45) NOT NULL,
  MEC_TELEFONE VARCHAR(45) NOT NULL,
  MEC_FUNCAO VARCHAR(45) NOT NULL,
  MEC_SENHA VARCHAR(45) NOT NULL
  );

-- Table COR_CORES
CREATE TABLE COR_CORES (
  COR_ID INT PRIMARY KEY AUTO_INCREMENT,
  COR_NOME VARCHAR(45) NOT NULL
  );

-- Table `EI_VEICULO
CREATE TABLE VEI_VEICULO (
  VEI_ID INT PRIMARY KEY AUTO_INCREMENT,
  VEI_NOME VARCHAR(45) NOT NULL,
  VEI_ANO INT NOT NULL,
  VEI_MODELO VARCHAR(45) NOT NULL,
  VEI_MARCA VARCHAR(45) NOT NULL,
  VEI_PLACA VARCHAR(45) NOT NULL,
  VEI_CHASSI VARCHAR(45) NOT NULL,
  VEI_QUILOMETRAGEM VARCHAR(45) NOT NULL,
  CLI_ID INT NOT NULL,
  COR_ID INT NOT NULL,
    FOREIGN KEY (CLI_ID)
    REFERENCES CLI_CLIENTE (CLI_ID),
    FOREIGN KEY (COR_ID)
    REFERENCES COR_CORES (COR_ID)
    );

-- Table ODS_ORDEM_SERVICO
CREATE TABLE ODS_ORDEM_SERVICO (
  ODS_ID INT PRIMARY KEY AUTO_INCREMENT,
  ODS_DATACRIACAO DATETIME NOT NULL,
  ODS_DATAFINALIZAR DATE NOT NULL,
  ODS_DESCRICAO VARCHAR(200) NOT NULL,
  ODS_VALORSERVICO DOUBLE NOT NULL,
  ODS_VALORTOTAL DOUBLE NOT NULL,
  MEC_ID INT NOT NULL,
  VEI_ID INT NOT NULL,
  ODS_VALOR_SERV DOUBLE NOT NULL,
  ODS_VALOR_PECA DOUBLE NOT NULL,
    FOREIGN KEY (MEC_ID)
    REFERENCES MEC_MECANICO (MEC_ID),
    FOREIGN KEY (VEI_ID)
    REFERENCES VEI_VEICULO (VEI_ID)
    );
    
-- Table PCS_PECAS
CREATE TABLE PCS_PECAS (
  PCS_ID INT PRIMARY KEY AUTO_INCREMENT,
  PCS_NOME VARCHAR(45) NOT NULL,
  PCS_VALOR DOUBLE NOT NULL,
  PCS_ESTADO TINYINT NOT NULL
  );
  
-- Table END_ENDERECO
CREATE TABLE END_ENDERECO (
  `END_ID` INT PRIMARY KEY AUTO_INCREMENT,
  END_CIDADE VARCHAR(45) NOT NULL,
  END_ESTADO VARCHAR(45) NOT NULL,
  END_BAIRRO VARCHAR(45) NOT NULL,
  END_CEP INT NOT NULL,
  CLI_ID INT NOT NULL,
    FOREIGN KEY (CLI_ID)
    REFERENCES CLI_CLIENTE (CLI_ID)
);

-- Table PUT_PECA_UTILIZADA
CREATE TABLE PUT_PECA_UTILIZADA (
  PUT_ID INT PRIMARY KEY AUTO_INCREMENT,
  PUT_QUANTIDADE INT NOT NULL,
  PUT_VALOR DOUBLE NOT NULL,
  PCS_ID INT NOT NULL,
  ODS_ID INT NOT NULL,
    FOREIGN KEY (PCS_ID)
    REFERENCES PCS_PECAS (PCS_ID),
    FOREIGN KEY (ODS_ID)
    REFERENCES ODS_ORDEM_SERVICO (ODS_ID)
);

-- Table SER_SERVICO
CREATE TABLE SER_SERVICO (
  SER_ID INT PRIMARY KEY AUTO_INCREMENT,
  SER_NOME VARCHAR(45) NOT NULL,
  SER_VALOR DOUBLE NOT NULL,
  SER_ESTADO TINYINT NOT NULL
);

-- Table SVU_SERV_UTILIZADO
CREATE TABLE SVU_SERV_UTILIZADO (
  SVU_ID INT PRIMARY KEY AUTO_INCREMENT,
  SVU_QUANTIDADE INT NOT NULL,
  SVU_VALOR DOUBLE NOT NULL,
  SER_SERVICO_SER_ID INT NOT NULL,
  ODS_ORDEM_SERVICO_ODS_ID INT NOT NULL,
    FOREIGN KEY (SER_SERVICO_SER_ID)
    REFERENCES SER_SERVICO (SER_ID),
    FOREIGN KEY (ODS_ORDEM_SERVICO_ODS_ID)
    REFERENCES ODS_ORDEM_SERVICO (ODS_ID)
);